### ISSUE TITLE
net/http patches bork on ruby 1.9.2

### ISSUE THREAD

**Issue by trampoline** [pyu10055/ntlm-http#8]
they work fine on 1.8.7, but raise an exception (below) on 1.9.2

workaround is to use httpclient for http conversation, and only use pyu-ntlm-http gem for net/ntlm authentication protocol support. if httpclient gem is installed, httpi does this by default

D, [2011-06-01T11:23:56.436533 #44064] DEBUG -- : HTTPI executes HTTP POST using the net_http adapter
NoMethodError: undefined method `to_hash' for #<Net::NTLM::Message::Type3:0x00000100a8f2e0>
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi/adapter/net_http.rb:110:in`respond_with'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi/adapter/net_http.rb:76:in `do_request'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi/adapter/net_http.rb:30:in`post'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi.rb:96:in `block in post'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi.rb:194:in`with_adapter'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/httpi-0.9.4/lib/httpi.rb:94:in `post'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/savon-0.9.2/lib/savon/soap/request.rb:25:in`block in response'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/savon-0.9.2/lib/savon/soap/request.rb:41:in `with_logging'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/savon-0.9.2/lib/savon/soap/request.rb:25:in`response'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/savon-0.9.2/lib/savon/client.rb:82:in `request'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/rews-0.5.2/lib/rews/folder.rb:155:in`block in find_item'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/rews-0.5.2/lib/rews/util.rb:111:in `with_error_check'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/rews-0.5.2/lib/rews/folder.rb:154:in`find_item'
    from /Users/mccraig/.rvm/gems/ruby-1.9.2-p180/gems/rews-0.5.2/lib/rews/folder.rb:187:in `find_item_id'
    from (irb):6
    from /Users/mccraig/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in`<main>'

**Comment by marttihyvonen** [comment]
Hey. I have similar problem with Ruby 1.9.3. How did you solve this?
